### ISSUE TITLE
Some URLs can not be loaded directly

### ISSUE THREAD

**Issue by BoogalooJB** [UNECE/Classification-Explorer#24]
For instance, in 0f2cd70 , we can navigate to [http://localhost:8080/classification/cpfr21/categorie/47.00.1](http://localhost:8080/classification/cpfr21/categorie/47.00.1), but cannot reload this page. Might be a router issue.

**Comment by EricDB** [comment]
Seems to have something to do with dots : see https://github.com/ReactTraining/react-router/issues/3409

**Comment by BoogalooJB** [comment]
It happens when the URL contains some dots. See https://github.com/UNECE/Model-Explorer/blob/22c96cdec0b1853c40b8d0d2e3a8132ca3b09526/src/js/routes.js#L16-L22 and https://github.com/UNECE/Model-Explorer/blob/22c96cdec0b1853c40b8d0d2e3a8132ca3b09526/src/js/routes.js#L68 for a workaround.
