### ISSUE TITLE
mainReducer is not found

### ISSUE THREAD

**Issue by romaintailhurat** [UNECE/Classification-Explorer#25]
With https://github.com/UNECE/Classification-Explorer/commit/152bf3cc69c8293b857b4fe54c1325bee62aedd3, there's an error when starting the application 

```
[IMPORT]: mainReducer from ../sparql/configure-sparql is undefined.classification.js:38485:4
[IMPORT]: mainReducer from ../sparql/configure-sparql is undefined.classification.js:38488:4
[IMPORT]: mainReducer from ../reducers/index is undefined.classification.js:38185:4
[IMPORT]: mainReducer from ../reducers/index is undefined.classification.js:38188:4
```
I think this comes with version 0.0.7 of sparql-connect.

**Comment by BoogalooJB** [comment]
Did you `npm install` after pulling ? Because it seems that it is not using 0.0.7, and it seems working on my computer.

**Comment by romaintailhurat** [comment]
So sorry, i was sure i did, but i didn't...  =(

It works fine with the upgrade.
