### ISSUE TITLE
Correspondence tables do not all show

### ISSUE THREAD

**Issue by FranckCo** [UNECE/Classification-Explorer#37]
For example, only one correspondence table appears on http://classifications.noknot.fr/classification/isicr4/details/isic, whereas there are in fact 4 (http://semstats.org/2016/challenge/classifications). 
ISIC 4 correspondence with CPC 2.1 does not show, for example. It does not show either on the CPC 2.1 page (http://classifications.noknot.fr/classification/cpcv2/details/cpc).

**Comment by BoogalooJB** [comment]
Partially fixed with 33a3d2ca794c52d21b47b7e2795870119f0cef44. But this is a workaround, lang should be set in the database for all the definitions.

Plus, in the database, some `xkos:compares` predicates refer to string literals instead of URIs.
