### ISSUE TITLE
Add language selection in SPARQL queries

### ISSUE THREAD

**Issue by FranckCo** [UNECE/Classification-Explorer#38]
Currently, when strings exist for different languages, the data is displayed in a mix of those languages. See for example http://classifications.noknot.fr/classification/isicr4/details/isic.

**Comment by BoogalooJB** [comment]
Language filtering has been adding to most of the queries (excluding search queries), by there are some side effects:  some labels are not available in english, hence the disappear (example: http://stamina-project.org/codes/cpfr21/cpf).

Plus, some labels are not in english but appear like they are (example: http://stamina-project.org/codes/ateco2007/ateco).
