### ISSUE TITLE
Clarify import in configure-store.js

### ISSUE THREAD

**Issue by FranckCo** [UNECE/Classification-Explorer#6]
In configure-store.js, we have:
`import mainReducer from '../reducers'`

This is a bit confusing for two reasons:
- It seems to rely only on a conventional Node behavior (http://stackoverflow.com/questions/35442174/javascript-import-from-folder-with-index-js)
- The export in reducers/index.js is anonymous

**Comment by BoogalooJB** [comment]
> It seems to rely only on a conventional Node behavior

We import css !!! What we do work in a given context, with a given module bundler, and in our case, a webpack config. I think relying on this convention is not the more obfuscating thing we do. Plus, that's what good libraries we use do : https://github.com/reactjs/redux/blob/master/src/index.js

> The export in reducers/index.js is anonymous

I don't get it. Is it about the `export default` syntax ? Or you mean it's an anonymous function ? In the second case, is it a bad thing ? If your concerns are about debugging, we can just name the function we export (but stay with the `export default` in ìndex.js`)

**Comment by BoogalooJB** [comment]
Thinking again, I think it can be an obfuscating part with no added value, so I agree it is a better option to explicitly import `index.js`.

**Comment by BoogalooJB** [comment]
Fix with 6503a2d3cda3bbce1a393e448ad907fdf20478ad
